[package]
name = "substreams-erc271-events"
version = "0.1.0"
description = "Substream ERC271 events tracking"
edition = "2021"
repository = "https://github.com/YaroShkvorets/substreams-erc271-events"
license = "Apache-2.0"

[lib]
name = "substreams"
crate-type = ["cdylib"]

[dependencies]
csv = "1.1"
ethereum-types = "0.15.1"
ethabi = "18"
prost = "0.13"
num-bigint = "0.4"
substreams = "0.6"
substreams-ethereum = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Required so that ethabi > ethereum-types build correctly under wasm32-unknown-unknown
[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["custom"] }

[build-dependencies]
anyhow = "1"
substreams-ethereum = "0.10"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
